#!/usr/bin/env bash

set -euo pipefail

PROFILE_FILE="/etc/profile.d/system-proxy.sh"
APT_FILE="/etc/apt/apt.conf.d/95system-proxy"
WGET_FILE="/etc/wgetrc"
ENV_FILE="/etc/environment"
UNSET_FILE="/tmp/unset-system-proxy.sh"
PROXY_VARS=(
  http_proxy
  https_proxy
  ftp_proxy
  all_proxy
  HTTP_PROXY
  HTTPS_PROXY
  FTP_PROXY
  ALL_PROXY
  no_proxy
  NO_PROXY
)

need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "请使用 root 权限运行：sudo bash $0"
    exit 1
  fi
}

urlencode() {
  local raw="${1}"
  local length="${#raw}"
  local i char

  for ((i = 0; i < length; i++)); do
    char="${raw:i:1}"
    case "${char}" in
      [a-zA-Z0-9.~_-]) printf '%s' "${char}" ;;
      *) printf '%%%02X' "'${char}" ;;
    esac
  done
}

read_required() {
  local prompt="${1}"
  local value=""

  while [[ -z "${value}" ]]; do
    read -r -p "${prompt}" value
    if [[ -z "${value}" ]]; then
      echo "不能为空，请重新输入。" >&2
    fi
  done

  printf '%s' "${value}"
}

read_secret() {
  local prompt="${1}"
  local value=""

  read -r -s -p "${prompt}" value
  echo >&2
  printf '%s' "${value}"
}

choose_scheme() {
  local choice=""

  while true; do
    echo "请选择连接方式：" >&2
    echo "  1) http" >&2
    echo "  2) sock5" >&2
    read -r -p "输入序号 [1-2]: " choice

    case "${choice}" in
      1) printf 'http'; return ;;
      2) printf 'socks5'; return ;;
      *) echo "无效选择，请输入 1 或 2。" >&2 ;;
    esac
  done
}

build_proxy_url() {
  local scheme="${1}"
  local host="${2}"
  local port="${3}"
  local username="${4}"
  local password="${5}"
  local userinfo=""

  if [[ -n "${username}" ]]; then
    userinfo="$(urlencode "${username}")"
    if [[ -n "${password}" ]]; then
      userinfo="${userinfo}:$(urlencode "${password}")"
    fi
    userinfo="${userinfo}@"
  fi

  printf '%s://%s%s:%s' "${scheme}" "${userinfo}" "${host}" "${port}"
}

backup_file() {
  local file="${1}"

  if [[ -f "${file}" ]]; then
    cp -a "${file}" "${file}.bak.$(date +%Y%m%d%H%M%S)"
  fi
}

remove_managed_block() {
  local file="${1}"

  if [[ -f "${file}" ]]; then
    sed -i '/# BEGIN SYSTEM_PROXY_MANAGED/,/# END SYSTEM_PROXY_MANAGED/d' "${file}"
  fi
}

write_unset_file() {
  local var=""

  {
    echo "#!/usr/bin/env bash"
    for var in "${PROXY_VARS[@]}"; do
      echo "unset ${var}"
    done
  } > "${UNSET_FILE}"

  chmod 0644 "${UNSET_FILE}"
}

write_profile() {
  local proxy_url="${1}"

  cat > "${PROFILE_FILE}" <<EOF
# BEGIN SYSTEM_PROXY_MANAGED
# Generated by set-system-proxy.sh
export http_proxy="${proxy_url}"
export https_proxy="${proxy_url}"
export ftp_proxy="${proxy_url}"
export all_proxy="${proxy_url}"
export HTTP_PROXY="${proxy_url}"
export HTTPS_PROXY="${proxy_url}"
export FTP_PROXY="${proxy_url}"
export ALL_PROXY="${proxy_url}"
export no_proxy="localhost,127.0.0.1,::1"
export NO_PROXY="localhost,127.0.0.1,::1"
# END SYSTEM_PROXY_MANAGED
EOF

  chmod 0644 "${PROFILE_FILE}"
}

write_environment() {
  local proxy_url="${1}"

  backup_file "${ENV_FILE}"
  remove_managed_block "${ENV_FILE}"
  cat >> "${ENV_FILE}" <<EOF
# BEGIN SYSTEM_PROXY_MANAGED
http_proxy="${proxy_url}"
https_proxy="${proxy_url}"
ftp_proxy="${proxy_url}"
all_proxy="${proxy_url}"
HTTP_PROXY="${proxy_url}"
HTTPS_PROXY="${proxy_url}"
FTP_PROXY="${proxy_url}"
ALL_PROXY="${proxy_url}"
no_proxy="localhost,127.0.0.1,::1"
NO_PROXY="localhost,127.0.0.1,::1"
# END SYSTEM_PROXY_MANAGED
EOF
}

write_apt() {
  local proxy_url="${1}"

  if [[ -d "/etc/apt/apt.conf.d" ]]; then
    cat > "${APT_FILE}" <<EOF
Acquire::http::Proxy "${proxy_url}";
Acquire::https::Proxy "${proxy_url}";
Acquire::ftp::Proxy "${proxy_url}";
EOF
    chmod 0644 "${APT_FILE}"
  fi
}

write_wget() {
  local proxy_url="${1}"

  if [[ -f "${WGET_FILE}" ]]; then
    backup_file "${WGET_FILE}"
    remove_managed_block "${WGET_FILE}"
    cat >> "${WGET_FILE}" <<EOF
# BEGIN SYSTEM_PROXY_MANAGED
use_proxy = on
http_proxy = ${proxy_url}
https_proxy = ${proxy_url}
ftp_proxy = ${proxy_url}
# END SYSTEM_PROXY_MANAGED
EOF
  fi
}

enable_proxy() {
  local scheme host port username password proxy_url

  scheme="$(choose_scheme)"
  host="$(read_required "请输入 IP 地址或域名: ")"
  port="$(read_required "请输入端口号: ")"
  read -r -p "请输入账号（没有则直接回车）: " username
  password=""
  if [[ -n "${username}" ]]; then
    password="$(read_secret "请输入密码（没有则直接回车）: ")"
  fi

  if ! [[ "${port}" =~ ^[0-9]+$ ]] || ((port < 1 || port > 65535)); then
    echo "端口号无效，应为 1-65535。"
    exit 1
  fi

  proxy_url="$(build_proxy_url "${scheme}" "${host}" "${port}" "${username}" "${password}")"

  backup_file "${PROFILE_FILE}"
  write_profile "${proxy_url}"
  write_environment "${proxy_url}"
  write_apt "${proxy_url}"
  write_wget "${proxy_url}"

  echo
  echo "系统代理已写入："
  echo "  ${PROFILE_FILE}"
  echo "  ${ENV_FILE}"
  [[ -f "${APT_FILE}" ]] && echo "  ${APT_FILE}"
  [[ -f "${WGET_FILE}" ]] && echo "  ${WGET_FILE}"
  echo
  echo "当前终端立即生效可执行：source ${PROFILE_FILE}"
  echo "桌面环境或已有终端通常需要重新登录后生效。"
}

disable_proxy() {
  local var=""

  rm -f "${PROFILE_FILE}" "${APT_FILE}"
  remove_managed_block "${ENV_FILE}"
  remove_managed_block "${WGET_FILE}"
  write_unset_file

  for var in "${PROXY_VARS[@]}"; do
    unset "${var}"
  done

  echo "已移除本脚本管理的系统代理配置。"
  echo "当前脚本进程内的代理变量已清理。"
  echo "如果你要让当前终端也立刻取消代理，请执行：source ${UNSET_FILE}"
  echo "也可以直接重新打开终端或重新登录。"
}

show_status() {
  echo "系统代理配置状态："
  if [[ -f "${PROFILE_FILE}" ]]; then
    echo "  shell profile: 已启用 (${PROFILE_FILE})"
    sed -n 's/^export http_proxy=//p' "${PROFILE_FILE}" | head -n 1
  else
    echo "  shell profile: 未启用"
  fi

  [[ -f "${APT_FILE}" ]] && echo "  apt: 已启用 (${APT_FILE})" || echo "  apt: 未启用或非 Debian/Ubuntu 系统"
  grep -q '# BEGIN SYSTEM_PROXY_MANAGED' "${ENV_FILE}" 2>/dev/null && echo "  environment: 已启用 (${ENV_FILE})" || echo "  environment: 未启用"
  grep -q '# BEGIN SYSTEM_PROXY_MANAGED' "${WGET_FILE}" 2>/dev/null && echo "  wget: 已启用 (${WGET_FILE})" || echo "  wget: 未启用"
}

test_exit_ip() {
  local profile_file="${PROFILE_FILE}"
  local urls=(
    "https://api.ipify.org"
    "https://ifconfig.me/ip"
    "https://ipinfo.io/ip"
  )
  local url=""

  if [[ -f "${profile_file}" ]]; then
    # shellcheck disable=SC1090
    source "${profile_file}"
  fi

  if ! command -v curl >/dev/null 2>&1; then
    echo "未找到 curl，请先安装 curl 后再测试。"
    exit 1
  fi

  echo "正在测试出口 IP..."
  for url in "${urls[@]}"; do
    if curl -fsSL --connect-timeout 8 --max-time 15 "${url}"; then
      echo
      return
    fi
  done

  echo "测试失败：无法获取出口 IP，请检查代理地址、端口、账号密码和网络连通性。"
  exit 1
}

main_menu() {
  local choice=""

  while true; do
    echo
    echo "Linux 永久系统代理配置"
    echo "  1) 启用/修改代理"
    echo "  2) 取消代理"
    echo "  3) 查看状态"
    echo "  4) 测试出口 IP"
    echo "  0) 退出"
    read -r -p "请选择操作: " choice

    case "${choice}" in
      1) enable_proxy ;;
      2) disable_proxy ;;
      3) show_status ;;
      4) test_exit_ip ;;
      0) exit 0 ;;
      *) echo "无效选择，请重新输入。" ;;
    esac
  done
}

need_root
main_menu
